
POST  http://localhost:4566/restapis/d8ix98hswp/prod/_user_request_/dynamo

{
    "id": 1,
    "name": "Serge",
    "createdAt": "1-1-22"
}

###GET

GET  http://localhost:4566/restapis/d8ix98hswp/prod/_user_request_/dynamo


###GET

GET  http://localhost:4566/restapis/d8ix98hswp/prod/_user_request_/hello
